# This file can be used to run the database locally
version: "3.2"
services: 
  mysql-db:
    container_name: mysql-db 
    build: ./
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
        - MYSQL_USER=root
        - MYSQL_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=password
  